# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\2T\Desktop\ui\simple.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QApplication
from second import MainWindow3
import subprocess

import tTox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2560, 1600)
        # palette = QtGui.QPalette()
        # pixmap = QtGui.QPixmap("07.jpg")
        # pixmap = pixmap.scaled(MainWindow.size(), QtCore.Qt.IgnoreAspectRatio)
        # palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(pixmap))
        # MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_openImage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openImage.setGeometry(QtCore.QRect(550, 1150, 131, 61))
        self.pushButton_openImage.setObjectName("pushButton_openImage")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(540, 1250, 151, 91))
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(240, 100, 800, 1000))
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setObjectName("label_image")
        self.label_image.setScaledContents(True)
        self.label_image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image1.setGeometry(QtCore.QRect(1500, 100, 800, 1000))
        self.label_image1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image1.setObjectName("label_image1")
        self.label_image1.setScaledContents(True)
        self.pushButton_trans = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trans.setGeometry(QtCore.QRect(1850, 1150, 121, 61))
        self.pushButton_trans.setObjectName("pushButton_trans")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(1840, 1250, 151, 91))
        self.pushButton_back.setObjectName("pushButton_back")
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1501, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_openImage.clicked.connect(self.openImage)
        self.pushButton_openImage.clicked.connect(self.saveImage)
        self.pushButton_start.clicked.connect(self.startdetect)
        self.pushButton_start.clicked.connect(self.showImage)
        self.pushButton_trans.clicked.connect(self.transTo)
        B = MainWindow3()
        self.pushButton_back.clicked.connect(lambda:{MainWindow.close(), B.show()})


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_openImage.setText(_translate("MainWindow", "打开图片"))
        self.pushButton_start.setText(_translate("MainWindow", "开始识别"))
        self.label_image.setText(_translate("MainWindow", "原始图像"))
        self.label_image1.setText(_translate("MainWindow", "识别图像"))
        self.pushButton_trans.setText(_translate("MainWindow", "转换为xml"))
        self.pushButton_back.setText(_translate("MainWindow", "选择二界面"))


    def openImage(self):  # 选择本地图片上传
        global imgName  # 这里为了方便别的地方引用图片路径，我们把它设置为全局变量
        imgName, imgType = QFileDialog.getOpenFileName(self.centralwidget, "打开图片", "", "*.jpg;;*.png;;All Files(*)")    # 弹出一个文件选择框，第一个返回值imgName记录选中的文件路径+文件名，第二个返回值imgType记录文件的类型
        jpg = QtGui.QPixmap(imgName).scaled(self.label_image.width(), self.label_image.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        position = imgName.rfind('/')
        global imgname 
        imgname = imgName[position+1: -4]
        self.label_image.setPixmap(jpg)  # 在label控件上显示选择的图片

    def saveImage(self):  # 保存图片到本地
        screenshot = QApplication.primaryScreen().grabWindow(self.label_image.winId())
        new_path = r'./detectImg/'
        # 将屏幕截图保存到指定路径下
        file_path = new_path + imgname + '.jpg'
        screenshot.save(file_path)


    def startdetect(self):  # 通过命令行执行detect
        command = ['python', 'detect.py', '--save-txt', '--project', 'result', '--name', 'exp']

        # 运行命令并捕获输出
        result = subprocess.run(command, capture_output=True, text=True)
        # 输出命令的标准输出和标准错误输出
        print(result.stdout)
        print(result.stderr)


    def showImage(self):  # 展示图片
        imgName2 = './result/exp/' + imgname + '.jpg'
        jpg = QtGui.QPixmap(imgName2).scaled(self.label_image1.width(), self.label_image1.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        self.label_image1.setPixmap(jpg)  # 在label控件上显示选择的图片


    def transTo(self):  # txt转换为xml文件
        tTox.runTrans()



class MainWindow2(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow2, self).__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow2()
    window.show()
    sys.exit(app.exec_())

