# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\2T\Desktop\ui\simple.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QApplication
import subprocess

import tTox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1100)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_openImage1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openImage1.setGeometry(QtCore.QRect(540, 240, 131, 61))
        self.pushButton_openImage1.setObjectName("pushButton_openImage")
        self.pushButton_openImage2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openImage2.setGeometry(QtCore.QRect(540, 640, 131, 61))
        self.pushButton_openImage2.setObjectName("pushButton_openImage2")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(295, 900, 151, 91))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_trans = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_trans.setGeometry(QtCore.QRect(940, 900, 151, 91))
        self.pushButton_trans.setObjectName("pushButton_trans")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(240, 100, 281, 341))
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setObjectName("label_image")
        self.label_image.setScaledContents(True)
        self.label_image2 = QtWidgets.QLabel(self.centralwidget)
        self.label_image2.setGeometry(QtCore.QRect(240, 500, 281, 341))
        self.label_image2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image2.setObjectName("label_image2")
        self.label_image2.setScaledContents(True)
        self.label_image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image1.setGeometry(QtCore.QRect(880, 100, 281, 341))
        self.label_image1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image1.setObjectName("label_image1")
        self.label_image1.setScaledContents(True)
        self.label_image3 = QtWidgets.QLabel(self.centralwidget)
        self.label_image3.setGeometry(QtCore.QRect(880, 500, 281, 341))
        self.label_image3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image3.setObjectName("label_image1")
        self.label_image3.setScaledContents(True)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1501, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_openImage1.clicked.connect(self.openImage)
        self.pushButton_openImage2.clicked.connect(self.openImage2)
        self.pushButton_openImage2.clicked.connect(self.saveImage2)
        self.pushButton_start.clicked.connect(self.startdetect)
        self.pushButton_start.clicked.connect(self.showImage)
        self.pushButton_start.clicked.connect(self.showImage2)
        self.pushButton_trans.clicked.connect(self.transTo)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_openImage1.setText(_translate("MainWindow", "打开图片一"))
        self.pushButton_openImage2.setText(_translate("MainWindow", "打开图片二"))
        self.pushButton_start.setText(_translate("MainWindow", "开始识别"))
        self.label_image.setText(_translate("MainWindow", "原始图像一"))
        self.label_image2.setText(_translate("MainWindow", "原始图像二"))
        self.label_image1.setText(_translate("MainWindow", "识别图像一"))
        self.label_image3.setText(_translate("MainWindow", "识别图像二"))
        self.pushButton_trans.setText(_translate("MainWindow", "转换为xml"))


    def openImage(self):  # 选择本地图片上传
        global imgName  # 这里为了方便别的地方引用图片路径，我们把它设置为全局变量
        imgName, imgType = QFileDialog.getOpenFileName(self.centralwidget, "打开图片", "", "*.jpg;;*.png;;All Files(*)")    # 弹出一个文件选择框，第一个返回值imgName记录选中的文件路径+文件名，第二个返回值imgType记录文件的类型
        jpg = QtGui.QPixmap(imgName).scaled(self.label_image.width(), self.label_image.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        position = imgName.rfind('/')
        global imgname 
        imgname = imgName[position+1: -4]
        self.label_image.setPixmap(jpg)  # 在label控件上显示选择的图片

    def openImage2(self):  # 选择本地图片上传
        global imgName2  # 这里为了方便别的地方引用图片路径，我们把它设置为全局变量
        imgName2, imgType = QFileDialog.getOpenFileName(self.centralwidget, "打开图片", "", "*.jpg;;*.png;;All Files(*)")    # 弹出一个文件选择框，第一个返回值imgName记录选中的文件路径+文件名，第二个返回值imgType记录文件的类型
        jpg = QtGui.QPixmap(imgName2).scaled(self.label_image2.width(), self.label_image2.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        position = imgName2.rfind('/')
        global imgname2 
        imgname2 = imgName2[position+1: -4]
        self.label_image2.setPixmap(jpg)  # 在label控件上显示选择的图片



    def saveImage2(self):  # 保存图片到本地
        screenshot = QApplication.primaryScreen().grabWindow(self.label_image.winId())
        new_path = r'./detectImg2/'
        # 将屏幕截图保存到指定路径下
        file_path = new_path + imgname + '.jpg'
        screenshot.save(file_path)
        screenshot = QApplication.primaryScreen().grabWindow(self.label_image2.winId())
        # 将屏幕截图保存到指定路径下
        file_path = new_path + imgname2 + '.jpg'
        screenshot.save(file_path)


    def startdetect(self):  # 通过命令行执行detect
        command = ['python', 'detect2.py', '--save-txt', '--project', 'result2', '--name', 'exp']

        # 运行命令并捕获输出
        result = subprocess.run(command, capture_output=True, text=True)
        # 输出命令的标准输出和标准错误输出
        print(result.stdout)
        print(result.stderr)


    def showImage(self):  # 展示图片
        imgName3 = './result2/exp/' + imgname + '.jpg'
        print(imgName3)
        jpg = QtGui.QPixmap(imgName3).scaled(self.label_image1.width(), self.label_image1.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        self.label_image1.setPixmap(jpg)  # 在label控件上显示选择的图片

    def showImage2(self):  # 展示图片
        imgName3 = './result2/exp/' + imgname2 + '.jpg'
        print(imgName3)
        jpg = QtGui.QPixmap(imgName3).scaled(self.label_image1.width(), self.label_image1.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        self.label_image3.setPixmap(jpg)  # 在label控件上显示选择的图片


    def transTo(self):  # txt转换为xml文件
        tTox.runTrans()



class MainWindow3(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow3, self).__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow3()
    window.show()
    sys.exit(app.exec_())

